name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Publish
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          path: dist/queueing-system-simulation
